package com.team2813.lib2813.util;

import edu.wpi.first.wpilibj.DriverStation;
import java.io.PrintStream;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.Optional;

record BuildConstantsRecord(
    String mavenName,
    int gitRevision,
    String gitSha,
    String gitBranch,
    ZonedDateTime gitSubmitTime,
    ZonedDateTime buildTime,
    long buildTimeMillis,
    int dirty)
    implements BuildConstants {
  private static final DateTimeFormatter DATE_FORMATTER =
      DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss z");

  /**
   * Constructs an instance from a class generated by the gversion Gradle plugin.
   *
   * <p>Instructions for using the gversion Gradle plugin can be found <a
   * href="https://docs.wpilib.org/en/stable/docs/software/advanced-gradlerio/deploy-git-data.html>here</a>.
   *
   * @param buildConstantsClass Specially built class that contains the robot code built-time
   *     constants.
   */
  static Optional<BuildConstantsRecord> fromGeneratedClass(Class<?> buildConstantsClass) {
    try {
      String mavenName = (String) buildConstantsClass.getDeclaredField("MAVEN_NAME").get(null);
      int gitRevision = (int) buildConstantsClass.getDeclaredField("GIT_REVISION").get(null);
      String gitSha = (String) buildConstantsClass.getDeclaredField("GIT_SHA").get(null);
      ZonedDateTime gitDate = extractZonedDateTime(buildConstantsClass, "GIT_DATE");
      String gitBranch = (String) buildConstantsClass.getDeclaredField("GIT_BRANCH").get(null);
      ZonedDateTime buildDate = extractZonedDateTime(buildConstantsClass, "BUILD_DATE");
      long buildTimeMillis =
          (long) buildConstantsClass.getDeclaredField("BUILD_UNIX_TIME").get(null);
      int dirty = (int) buildConstantsClass.getDeclaredField("DIRTY").get(null);

      return Optional.of(
          new BuildConstantsRecord(
              mavenName,
              gitRevision,
              gitSha,
              gitBranch,
              gitDate,
              buildDate,
              buildTimeMillis,
              dirty));
    } catch (DateTimeParseException e) {
      // Handled in extractZonedDateTime
    } catch (NoSuchFieldException | IllegalAccessException e) {
      String message =
          "Could not extract build constants from "
              + buildConstantsClass.getSimpleName()
              + ": "
              + e.getMessage();
      DriverStation.reportWarning(message, e.getStackTrace());
    }
    return Optional.empty();
  }

  String gitSubmitTimeString() {
    return DATE_FORMATTER.format(gitSubmitTime);
  }

  String buildTimeString() {
    return DATE_FORMATTER.format(buildTime);
  }

  void write(PrintStream stream) {
    stream.println("MavenName:     " + mavenName);
    stream.println("GitRevision:   " + gitRevision);
    stream.println("GitSha:        " + gitSha);
    stream.println("GitDate:       " + gitSubmitTimeString());
    stream.println("GitBranch:     " + gitBranch);
    stream.println("BuildDate:     " + buildTimeString());
    stream.println("BuildUnixTime: " + buildTimeMillis);
    stream.println("Dirty:         " + dirty);
  }

  private static ZonedDateTime extractZonedDateTime(Class<?> buildConstantsClass, String fieldName)
      throws NoSuchFieldException, IllegalAccessException {
    try {
      String value = (String) buildConstantsClass.getDeclaredField(fieldName).get(null);
      return ZonedDateTime.parse(value, DATE_FORMATTER);
    } catch (DateTimeParseException e) {
      String message =
          "Could not extract build constants from "
              + buildConstantsClass.getSimpleName()
              + " due to unparsable date-time value for "
              + fieldName
              + ": "
              + e.getMessage();
      DriverStation.reportWarning(message, e.getStackTrace());
      throw e;
    }
  }
}
